#!/bin/sh

VERSION="char *version = PACKAGE_FULLNAME;";

# Doesn't account for variances in date and I don't care.
DATETIME="char *date = \"`date`\";"

if [ -f version.c ]; then
	mv version.c version.c.last
fi

# Logic for the older BSD's
platlogic=cat <<EOF
#ifdef BSD4_2
char *platform = "4.2BSD VAX";
#elif BSD4_3
char *platform = "4.3BSD VAX"; /* XXX not always a vax! */
#elif BSD4_4
/* XXX I feel lazy. Not gonna bother checking for specifics */
char *platform = "4.4BSD VAX";
#else
char *platform = "Unknown";
#endif
EOF

# Check for uname
PLATFORM=`/bin/sh -c "uname -sm" 2>/dev/null || echo "None"`

if [ "$PLATFORM" = "None" ]; then
	PLATFORM="$platlogic"
else
	PLATFORM="char *platform = \"$PLATFORM\";"
fi

cat >version.c <<EOF
/* version.c - symbols for export
 * This file is automatically generated. Don't touch!
 */

#include "ircd.h"

$VERSION
$DATETIME
$PLATFORM
EOF
