#!/bin/sh

OUT=version.c
[ -f $OUT ] && mv $OUT $OUT.last

echo '/* auto-generated by version.sh */' > $OUT
echo '#include "ircd.h"' >> $OUT

echo "char *version = PACKAGE_FULLNAME;" >> $OUT

echo "char *date = \"`date -u +%F\ %H:%M\ UTC`\";" >> $OUT

echo "char *platform = \"$(uname -sm)\";"  >> $OUT

echo "char *revision = \"$(git log -1 --pretty=oneline | cut -d' ' -f1 2>/dev/null)\";" >> $OUT
